import type { Complaint } from './types';

export const mockComplaints: Complaint[] = [
  {
    _id: 'complaint-001',
    title: 'Large Pothole on Elm Street',
    description: 'There is a very large and dangerous pothole in the middle of Elm Street, near the intersection with Oak Avenue. It has already caused damage to one vehicle. It needs urgent repair.',
    location: { type: 'Point', coordinates: [75.85, 30.91] },
    citizenId: 'citizen-123',
    departmentId: 'Public Works',
    priority: 'High',
    severity: 'High',
    tags: ['pothole', 'road damage', 'traffic hazard'],
    category: 'Infrastructure',
    deadline: new Date('2024-08-15T23:59:59Z'),
    status: 'In Progress',
    createdAt: new Date('2024-08-05T10:00:00Z'),
    applicationNumber: 'CN-583920',
    history: [
      {
        date: new Date('2024-08-05T10:00:00Z'),
        action: 'Complaint Submitted',
        updatedBy: 'citizen-123',
        status: 'Pending',
        comment: 'Citizen submitted the complaint.',
      },
      {
        date: new Date('2024-08-05T11:30:00Z'),
        action: 'Assigned to Department',
        updatedBy: 'control-room-01',
        status: 'In Progress',
        comment: 'Assigned to Public Works.',
      },
    ],
    createdBy: 'citizen-123',
  },
  {
    _id: 'complaint-002',
    title: 'Streetlight Outage at Park Entrance',
    description: 'The streetlight at the main entrance of Central Park is not working. It is very dark and feels unsafe at night.',
    location: { type: 'Point', coordinates: [75.84, 30.90] },
    citizenId: 'citizen-123',
    departmentId: 'Utilities',
    priority: 'Medium',
    severity: 'Medium',
    tags: ['streetlight', 'outage', 'safety'],
    category: 'Utility',
    deadline: new Date('2024-08-10T23:59:59Z'),
    status: 'Resolved',
    createdAt: new Date('2024-08-01T14:00:00Z'),
    applicationNumber: 'CN-583712',
    resolutionDetails: {
        status: "Resolved",
        resolvedBy: "dept-user-02",
        resolutionDate: new Date('2024-08-03T16:00:00Z'),
        comments: "Bulb replaced and fixture tested."
    },
    history: [
        {
            date: new Date('2024-08-01T14:00:00Z'),
            action: 'Complaint Submitted',
            updatedBy: 'citizen-123',
            status: 'Pending',
            comment: 'Citizen submitted the complaint.',
        },
        {
            date: new Date('2024-08-03T16:00:00Z'),
            action: 'Complaint Resolved',
            updatedBy: 'dept-user-02',
            status: 'Resolved',
            comment: 'Technician replaced the faulty bulb.',
        }
    ],
    createdBy: 'citizen-123',
  },
  {
    _id: 'complaint-003',
    title: 'Illegal Dumping in River Valley',
    description: 'A large amount of construction debris has been illegally dumped near the river bank. It is an environmental hazard.',
    location: { type: 'Point', coordinates: [75.86, 30.92] },
    citizenId: 'citizen-456',
    departmentId: 'Environment',
    priority: 'High',
    severity: 'Critical',
    tags: ['illegal dumping', 'waste', 'pollution'],
    category: 'Environment',
    deadline: new Date('2024-07-28T23:59:59Z'),
    status: 'Overdue',
    createdAt: new Date('2024-07-25T09:00:00Z'),
    applicationNumber: 'CN-583555',
    history: [
        {
            date: new Date('2024-07-25T09:00:00Z'),
            action: 'Complaint Submitted',
            updatedBy: 'citizen-456',
            status: 'Pending',
            comment: 'Citizen submitted the complaint.',
        }
    ],
    createdBy: 'citizen-456',
  },
    {
    _id: 'complaint-004',
    title: 'Broken playground swing',
    description: 'The main swing in the kids area of sunnyside park is broken and dangerous.',
    location: { type: 'Point', coordinates: [75.855, 30.905] },
    citizenId: 'citizen-123',
    departmentId: 'Public Works',
    priority: 'Medium',
    severity: 'Medium',
    tags: ['playground', 'safety', 'park'],
    category: 'Infrastructure',
    deadline: new Date('2024-08-20T23:59:59Z'),
    status: 'Pending',
    createdAt: new Date('2024-08-08T11:00:00Z'),
    applicationNumber: 'CN-584011',
    history: [
      {
        date: new Date('2024-08-08T11:00:00Z'),
        action: 'Complaint Submitted',
        updatedBy: 'citizen-123',
        status: 'Pending',
        comment: 'Citizen submitted the complaint.',
      },
    ],
    createdBy: 'citizen-123',
  },
  ...Array.from({ length: 10 }, (_, i) => ({
    _id: `complaint-pw-00${i + 1}`,
    title: `Faded Lane Markings on Highway ${i + 1}`,
    description: `The lane markings on Highway ${i + 1} are severely faded, causing confusion for drivers, especially at night.`,
    location: { type: 'Point' as const, coordinates: [75.85 + i * 0.001, 30.91 + i * 0.001] as [number, number] },
    citizenId: 'citizen-789',
    departmentId: 'Public Works',
    priority: 'Medium' as const,
    severity: 'Medium' as const,
    tags: ['road safety', 'lane marking', 'highway'],
    category: 'Infrastructure' as const,
    deadline: new Date(`2024-08-${16 + i}T23:59:59Z`),
    status: 'Pending' as const,
    createdAt: new Date(`2024-08-06T10:00:${i < 10 ? '0' : ''}${i}Z`),
    applicationNumber: `CN-5840${12 + i}`,
    history: [
      {
        date: new Date(`2024-08-06T10:00:${i < 10 ? '0' : ''}${i}Z`),
        action: 'Complaint Submitted',
        updatedBy: 'citizen-789',
        status: 'Pending' as const,
        comment: 'Citizen submitted the complaint.',
      },
    ],
    createdBy: 'citizen-789',
  })),
];
